name: Docker Image CI

on:
  push:
    tags:
     - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to github docker repository 
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u shadowfish07 --password-stdin
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          npm run docker-build 
          docker tag online-drawer/front-end ghcr.io/shadowfish07/online-drawer/front-end:${{ env.RELEASE_VERSION }}
          docker tag online-drawer/websocket-server ghcr.io/shadowfish07/online-drawer/websocket-server:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/shadowfish07/online-drawer/front-end:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/shadowfish07/online-drawer/websocket-server:${{ env.RELEASE_VERSION }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: githubAction
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ghcr.io/shadowfish07/online-drawer/front-end:${{ env.RELEASE_VERSION }}
            docker pull ghcr.io/shadowfish07/online-drawer/websocket-server:${{ env.RELEASE_VERSION }}
            docker stop online-drawer-front-end online-drawer-websocket-server
            docker rm online-drawer-front-end online-drawer-websocket-server
            docker run -p 8081:8081 -d --name online-drawer-websocket-server --network online-drawer ghcr.io/shadowfish07/online-drawer/websocket-server:${{ env.RELEASE_VERSION }}
            docker run -p 8080:8080 -d --name online-drawer-front-end --network online-drawer ghcr.io/shadowfish07/online-drawer/front-end:${{ env.RELEASE_VERSION }}
              
