name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to github docker repository 
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u shadowfish07 --password-stdin
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          npm run docker-build 
          docker tag online-drawer/front-end online-drawer/front-end:$(date +%s)
          docker tag online-drawer/websocket-server online-drawer/websocket-server:$(date +%s)
          docker push ghcr.io/shadowfish07/online-drawer/front-end:$(date +%s)
          docker push ghcr.io/shadowfish07/online-drawer/websocket-server:$(date +%s)
        
